table gold_customer_installment_correlation
	lineageTag: 864433b6-1917-4333-9938-1728ded30966

	column price_threshold_tier
		dataType: string
		lineageTag: 270a0c5a-8fe0-4280-86fe-cc7acc500d60
		summarizeBy: none
		sourceColumn: price_threshold_tier

		annotation SummarizationSetBy = Automatic

	column payment_type
		dataType: string
		lineageTag: 8ed0a286-938f-4b3f-a252-53ee80f3e878
		summarizeBy: none
		sourceColumn: payment_type

		annotation SummarizationSetBy = Automatic

	column total_orders
		dataType: int64
		formatString: 0
		lineageTag: f129e848-ba70-4dae-9abd-c8d203349e8c
		summarizeBy: sum
		sourceColumn: total_orders

		annotation SummarizationSetBy = Automatic

	column avg_installments
		dataType: double
		lineageTag: f3ad6ac5-9499-45b8-8fcb-ebb7a631c508
		summarizeBy: sum
		sourceColumn: avg_installments

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_financial_volume
		dataType: double
		lineageTag: 88365746-12be-487b-a1df-f7349f53ea1c
		summarizeBy: sum
		sourceColumn: total_financial_volume

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition gold_customer_installment_correlation = m
		mode: import
		source =
				let
				    Source = Databricks.Catalogs("adb-7405609590065761.1.azuredatabricks.net", "/sql/1.0/warehouses/d88b28148595f531", [Catalog=null, Database=null, QueryTags=null, EnableAutomaticProxyDiscovery=null, Implementation="2.0", Protocol=null]),
				    db_retail_analytics_Database = Source{[Name="db_retail_analytics",Kind="Database"]}[Data],
				    supply_chain_project_Schema = db_retail_analytics_Database{[Name="supply_chain_project",Kind="Schema"]}[Data],
				    gold_customer_installment_correlation_Table = supply_chain_project_Schema{[Name="gold_customer_installment_correlation",Kind="Table"]}[Data],
				    #"Replaced Value" = Table.ReplaceValue(gold_customer_installment_correlation_Table,"$0-$100","$50-$100",Replacer.ReplaceText,{"price_threshold_tier"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","$0-$250","$100-$250",Replacer.ReplaceText,{"price_threshold_tier"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","$0-$500","$250-$500",Replacer.ReplaceText,{"price_threshold_tier"})
				in
				    #"Replaced Value2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

